### ISSUE TITLE
EAPI 7

### ISSUE THREAD

**Issue by TheEvilSkeleton** [deu/palemoon-overlay#105]
I just wanted to inform you that we have written ebuilds that use EAPI 7. We are planning to remove those ebuilds some day as we stopped maintaining it. If you want, you can use our ebuilds to use EAPI 7, as the current ebuilds provided by you are still using EAPI 6.

- https://gitlab.com/src_prepare/src_prepare-overlay/-/tree/069c86d280b05fd0e22619ee4d360b18ec47ab2c/www-client/palemoon
- https://gitlab.com/src_prepare/src_prepare-overlay/-/blob/069c86d280b05fd0e22619ee4d360b18ec47ab2c/eclass/palemoon-v1.eclass

**Comment by xgqt** [comment]
* today

;^)
