### ISSUE TITLE
Please bump version to 29.1.1

### ISSUE THREAD

**Issue by Cerberios** [deu/palemoon-overlay#110]
Hello there! Dear maintainers, can You please bump version and make available latest release as 29.1.1?
Thank You!

**Comment by CaseOf** [comment]
Take a look at https://github.com/deu/palemoon-overlay/pull/109

**Comment by CaseOf** [comment]
Also until @deu merges it you can do:
```
cd /var/db/repos/palemoon
gît remote set-url origin https://github.com/CaseOf/palemoon-overlay.git
```

**Comment by Cerberios** [comment]
Great thanks! Trying to compile
