### ISSUE TITLE
Maintainership offering

### ISSUE THREAD

**Issue by CaseOf** [deu/palemoon-overlay#115]
Dear deu,
 
I have been contributing to your overlay for almost a year now. I'm grateful that you've entrusted me with a measure of responsibility regarding your overlay by merging my pull requests reliably and consistently.
 
I've noticed lately that you seem to be dealing with a situation that prevents you from contributing to the overlay more often, and unfortunately this has slowed down development. I hope things get better for you soon.
 
Therefore, I would like to ask you to trust me further with the overlay project by giving me permission to push my commits directly in order to take some of the maintainence burden off of you.
 
Depending on your schedule, if you are planning to return and work on the overlay soon, perhaps this isn't necessary. But if you will continue to be pressed for time, I would appreciate it if you could give me write access to make updates smoother.
 
Sincerely, 
 
Case_Of

**Comment by CaseOf** [comment]
Thank you.

**Comment by CaseOf** [comment]
Dear @deu,
@l29ah wish to contribute on your overlay.
I did merge some of his pull requests already.
I think he's doing a valuable and trustworthy work here.
I would like to ask you if you would give him commit access to your overlay.
It would help to a good maintainership in long term.
Sincerely,
Case_Of

**Comment by deu** [comment]
Done.
