### ISSUE TITLE
pyt: bad interpreter

### ISSUE THREAD

**Issue by Massimo-B** [deu/palemoon-overlay#37]
Ok, I tried the build by switching gcc to x86_64-pc-linux-gnu-4.9.4.
If this is something about python, I tried both python 2.7.12 and 3.4.5.

```
 0:17.05 js/src> creating ./config.status
 0:17.05 js/src> /bin/sh: ./config.status: /mnt/ssd/tmp.notmpfs/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/obj-x86_64-unknown-linux-gnu/_virtualenv/bin/pyt: bad interpreter: No such file or directory
 0:20.23 *** Fix above errors and then restart with\
 0:20.23                "/usr/bin/gmake -f client.mk build"
 0:20.23 gmake: *** [client.mk:363: configure] Error 1
 * ERROR: www-client/palemoon-27.1.0::palemoon failed (configure phase):

```

**Comment by nick87720z** [comment]
Similar case... not just python

` 1:04.46 js/src> updating cache /var/calculate/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/obj-x86_64-unknown-linux-gnu/config.cache`
`1:04.46 js/src> creating ./config.status`
`1:04.46 js/src> /bin/sh: ./config.status: /var/calculate/tmp/portage/www-client/palemoon-27.1.0/work/palemoon-27.1.0/ob: bad interpreter: No such file or directory`
`1:04.46 *** Fix above errors and then restart with\`
`1:04.46                "/usr/bin/gmake -f client.mk build"`
`1:04.47 gmake: *** [client.mk:363: configure] Error 1`

**Comment by pvgoran** [comment]
Same here:
>  0:51.33 js/src> /bin/sh: ./config.status: /volumes/temp-fs/vartmp/portage/www-client/palemoon-27.4.0/work/palemoon-27.4: bad interpreter: Permission denied

Apparently the path to interpreter in the "shebang" line inside `config.status` gets truncated to 77 characters.

Everyone who reported this bug seem to have the portage build directory (which is normally /var/tmp/portage) at some alternative location: `/mnt/ssd/tmp.notmpfs/portage`, `/var/calculate/tmp/portage`, `/volumes/temp-fs/vartmp/portage` (in my case, `/var/tmp` is a symlink to `/volumes/temp-fs/vartmp`).

Apparently this causes the full path to the interpreter (`/volumes/temp-fs/vartmp/portage/www-client/palemoon-27.4.0/work/palemoon-27.4.0/obj-x86_64-unknown-linux-gnu/_virtualenv/bin/python` in my case, which is 131 characters) to hit the 127 character limit imposed by the kernel. So the kernel refuses to execute the file, then bash tries to execute the file by itself but truncates the interpreter path even more (to 77 characters) and finally gives up.

**Comment by deuiore** [comment]
@Massimo-B could you please check if this is fixed for you now?

**Comment by pvgoran** [comment]
At least for me, compilation now successfully completes.

**Comment by nick87720z** [comment]
Works for me too.
I have enabled all system-lib flags, excepting hunspell. By some reason it locked at =hunspell-1.6.0, while portage has only 1.6.1 as stable (and 1.6.2 as experimental).

**Comment by deuiore** [comment]
@nick87720z 
The reason is that the build fails if you try to compile it with any version but that. See #51.
I'll just remove the USE flag for now.

**Comment by nick87720z** [comment]
Btw, i made it with gcc5, adding proper variable in make.conf)

**Comment by pvgoran** [comment]
For me, as soon as this bug was fixed, palemoon was successfully built with gcc5 without any additional effort. It's also running without any issues for 2 days already.
