### ISSUE TITLE
branding violation

### ISSUE THREAD

**Issue by nick87720z** [deu/palemoon-overlay#61]
Explained here: https://github.com/jasperla/openbsd-wip/issues/86
Don't know, since what version...
Last version, which i have built with branding (current) is 27.7.2. Now i tried to upgrade to 27.8.3 and got branding violation.

Appart of this exact error (which however, doesn't stop configure process), it tries to test for <sys/int_types.h> header, which doesn't preset on my system - right after <stdint.h> test.

For now i have just disabling it.
Cofigure with branding completes if "system-lib" options are disabled.
Would be good to add this to REQUIRED_USE.

**Comment by deu** [comment]
I'm not sure what to make of the <sys/int_types.h> test. From what you said I don't think it's related to the branding violation warning, or did I misunderstand? What GCC version are you using?

The REQUIRED_USE update is a good idea and I'll be doing that.
