### ISSUE TITLE
Add gcc-6 workarounds

### ISSUE THREAD

**Issue by mittorn** [deu/palemoon-overlay#62]
Adding " -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2" to cflags seems to fix new gcc issues.

**Comment by deu** [comment]
I'd rather not mess with CFLAGS without proper testing and confirmation from upstream.

It won't be long now until Pale Moon 28 is released and we can forget about having to deal with old masked gcc versions or build errors, so I don't think it's worth to overthink this now.

Thanks anyway.
