### ISSUE TITLE
compile error with 27.9.4

### ISSUE THREAD

**Issue by joe9** [deu/palemoon-overlay#68]
Hello,

I have this compile error when trying to build 27.9.4.

Thanks

[www-client:palemoon-27.9.4:20180722-004513.log.txt](https://github.com/deu/palemoon-overlay/files/2216637/www-client.palemoon-27.9.4.20180722-004513.log.txt)

**Comment by thecodder** [comment]
You use gcc-7.3.0, this version is not compatible.
Unmask and install old GCC as second: emerge =sys-devel/gcc-4.9.4

add in /etc/portage/env/www-client/palemoon 
something like that:
GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-gcc
CC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-gcc
CXX=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-g++
CPP=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-cpp
AR=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-gcc-ar
NM=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-gcc-nm
RANLIB=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-gcc-ranlib
FORTRAN=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-gfortran
GCOV=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/x86_64-pc-linux-gnu-gcov

next: emerge palemoon

**Comment by deu** [comment]
As stated above, you were using an unsupported GCC version.
Pale Moon 28 is going to be able to be built with 7.3.
