### ISSUE TITLE
palemoon-28.3.0 doesn't show any suggestions in URL Bar

### ISSUE THREAD

**Issue by pvgoran** [deu/palemoon-overlay#72]
I'm building it like this:

[ebuild   R   ~] www-client/palemoon-28.3.0::palemoon  USE="dbus devtools gnome gtk2 jemalloc optimize pulseaudio threads -debug (-gtk3) -necko-wifi -official-branding -valgrind" CPU_FLAGS_X86="sse sse2"

It builds successfully, but the browser doesn't show the suggestions drop-down, even if I click the triangle at the right of the URL Bar. Creating a new PaleMoon profile didn't help.

I had the same problem with 28.2.2. In version 28.0.0, it did work. If I run the binary version (palemoon-bin-28.2.2 or 28.3.0) with the same PaleMoon profile, suggestions work as well.

**Comment by deu** [comment]
Sorry, closing this because it's obsolete now. Feel free to open a new issue if you're still having this problem.

**Comment by pvgoran** [comment]
In fact, it suddenly started working properly a couple of months ago.
