### ISSUE TITLE
palemoon-28.4.0 produces the unsupported compiler warning regardless of the selected compiler

### ISSUE THREAD

**Issue by l29ah** [deu/palemoon-overlay#73]
```
 * Checking compiler profile...
 * Building Pale Moon with a compiler other than a supported gcc version
 * may result in an unstable build.
 * Be aware that building Pale Moon with an unsupported compiler
 * means that the official support channels may refuse to offer any
 * kind of help in case the build fails or the browser behaves incorrectly.
 * Supported GCC versions: 4.9, 5.4, 7.3, 8.2, 8.3
 * Selected GCC version: 8.2
 * To disable this warning unset the PALEMOON_ENABLE_UNSUPPORTED_COMPILERS
 * environment variable.
```

**Comment by deu** [comment]
That warning is always displayed when you have the PALEMOON_ENABLE_UNSUPPORTED_COMPILERS variable set, whether your selected compiler is in fact supported or not.

I prefer it that way so I always know which compiler version Pale Moon is going to be built with when I'm testing different ones, and as a reminder that the PALEMOON_ENABLE_UNSUPPORTED_COMPILERS is currently set, which should be an exceptional occurrence.

Unsetting PALEMOON_ENABLE_UNSUPPORTED_COMPILERS makes the warning go away, and if you were to use an unsupported compiler you'd actually get an error, not just a warning.
