### ISSUE TITLE
palemoon-28.6.1 doesn't utilize vaapi for video playback

### ISSUE THREAD

**Issue by l29ah** [deu/palemoon-overlay#76]
Making video playback really slow and battery-wasting. As observed by https://www.youtube.com/watch?v=Pyl85gw2NL4 consuming 350% CPU with palemoon but only 5% with mpv on the same system in 4k quality. `about:support` tells me
```
HW_COMPOSITING	
blocked by default: Acceleration blocked by platform
OPENGL_COMPOSITING	
unavailable by default: Hardware compositing is disabled
Hardware H264 Decoding	No
```

**Comment by deu** [comment]
Check your `Preferences -> General -> Hardware Acceleration (HWA)` options.

**Comment by l29ah** [comment]
It's enabled.

**Comment by deu** [comment]
I can't really reproduce this then.
Could you check if you have the same problem with `palemoon-bin` (which is the official binary) and in that case report the issue to the official Pale Moon channels?

**Comment by l29ah** [comment]
Do you mean it doesn't consume CPU in your case?
Thanks, i will check it.
