### ISSUE TITLE
palemoon-28.7.2 with gcc-9.2.0, password completion not working

### ISSUE THREAD

**Issue by Massimo-B** [deu/palemoon-overlay#77]
First of all, eselect is using the repo https://github.com/gentoo-mirror/palemoon.git, is this synchronized to this one?

After reading in the releasenotes [1] that PM has fixed some parts towards newer compilers, I tried building www-client/palemoon-28.7.2 with
PALEMOON_ENABLE_UNSUPPORTED_COMPILERS=1 emerge -atv palemoon
with
x86_64-pc-linux-gnu-9.2.0

It's working well since days, only issue that the password or form completion does not open the selection box. Typing a username the matching password is still filled.

[1] v28.7.2 (2019-10-29): Worked around a gcc9 compiler issue that would prevent building with it.

**Comment by CaseOf** [comment]
Hi,
Gentoo Mirror organization is an official Gentoo organization and automatically sync overlays in https://overlays.gentoo.org.

**Comment by deu** [comment]
I can't see any issue with the newest version.
Feel free to open another issue if you're still having this problem.
