### ISSUE TITLE
palemoon-28.9.2: 9G are not enough

### ISSUE THREAD

**Issue by sedimentation-fault** [deu/palemoon-overlay#80]
In the ebuild for _palemoon-28.9.2_ you have

`REQUIRED_BUILDSPACE='9G'`

This is not enough. I have PORTAGE_TMPDIR on a RAM disk with 16 GB, of which 12 GB were occupied by _palemoon_ at the end of compilation - and _it was not enough_! I got a _'no more space left on device'_ error just when, after 2 hours of compilation, the ebuild was about to start the install phase.

Setting

`REQUIRED_BUILDSPACE='15G'`

(and taking care to have not 'just' 12 GB, but full 15 GB free on PORTAGE_TMPDIR) lets it finish without problems. Why 15 GB should be necessary to compile and install a _browser_ though, is a different question...

P.S.: Well, maybe 12.5 GB would have also sufficed, but I did not have the patience to binary dissect the 3 GB between 12 and 15...

**Comment by sedimentation-fault** [comment]
Even with 16450856 bytes free on PORTAGE_TMPDIR, I get a _'no space left on device'_ error during stripping:

```
strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/lib64/palemoon/libsoftokn3.so
   /usr/lib64/palemoon/libnssdbm3.so
   /usr/lib64/palemoon/libmozavutil.so
...
   /usr/lib64/palemoon/libnss3.so
   /usr/lib64/palemoon/libxul.so
   /usr/lib64/palemoon/libmozavcodec.so
x86_64-pc-linux-gnu-objcopy:/xxxx/portage/www-client/palemoon-28.9.2-r1/image/usr/lib64/palemoon/st9OUZ6G[.debug_info]: No space left on device
x86_64-pc-linux-gnu-objcopy:/xxxx/portage/www-client/palemoon-28.9.2-r1/image/usr/lib64/palemoon/st9OUZ6G: No space left on device
```
However, this does not affect installation - I guess the two objects above simply do not get stripped. The final size of build directory is slightly over 9 GB:

 `* Final size of build directory: 10350400 KiB (9.8 GiB)`

but given the stripping error above, I consider my 16GB of free space rather a minimum.

**Comment by deu** [comment]
I've just checked, and indeed the build directory reaches a size of almost 15G.

I will take your suggestion and from the next release I will set the ebuild REQUIRED_BUILDSPACE to 16G so we can have some margin.
