### ISSUE TITLE
palemoon-28.9.3 libmozavcodec.so] Error 1

### ISSUE THREAD

**Issue by custom82** [deu/palemoon-overlay#83]
^[7^[8^[[1G^[[J^[[34m66:00.32^[(B^[[m
^[7^[8^[[1G^[[J^[[34m66:00.32^[(B^[[m ../../../build/unix/gold/ld: error: /var/tmp/portage/www-client/palemoon-28.9.3/work/palemoon-28.9.3/o/media/ffvpx/libavcodec/flac_parser.o: multiple definition of 'ff_flac_parser'
^[7^[8^[[1G^[[J^[[34m66:00.32^[(B^[[m ../../../build/unix/gold/ld: /var/tmp/portage/www-client/palemoon-28.9.3/work/palemoon-28.9.3/o/media/ffvpx/libavcodec/dummy_funcs.o: previous definition here
^[7^[8^[[1G^[[J^[[34m66:00.32^[(B^[[m collect2: error: ld returned 1 exit status
^[7^[8^[[1G^[[J^[[34m66:00.32^[(B^[[m gmake[4]: *** [/var/tmp/portage/www-client/palemoon-28.9.3/work/palemoon-28.9.3/platform/config/rules.mk:773: libmozavcodec.so] Error 1
^[7^[8^[[1G^[[J^[[34m66:00.33^[(B^[[m gmake[3]: *** [/var/tmp/portage/www-client/palemoon-28.9.3/work/palemoon-28.9.3/platform/config/recurse.mk:71: media/ffvpx/libavcodec/target] Error 2
^[7^[8^[[1G^[[J^[[34m66:00.33^[(B^[[m gmake[3]: *** Waiting for unfinished jobs....

**Comment by deu** [comment]
This isn't nearly enough data to figure out what the problem could be. If you still have this issue feel free to reply with more information about your system.
