### ISSUE TITLE
Problem building with GTK3

### ISSUE THREAD

**Issue by tjerry** [deu/palemoon-overlay#84]
I'd like to build Palemoon with GTK3.

In _package.use_ I have:
`www-client/palemoon -gtk2 gtk3`

But `emerge` results in :
_The following REQUIRED_USE flag constraints are unsatisfied:
    exactly-one-of ( gtk2 gtk3 )_

Is GTK3 USE flag supported?

**Comment by mittorn** [comment]
it is masked, you need www-client/palemoon -gtk3 in /etc/portage/profile/package.use.mask

**Comment by deu** [comment]
The `gtk3` USE flag is masked because building with it isn't really supported. See [this](https://wiki.gentoo.org/wiki//etc/portage/profile/use.mask) for more details about masked USE flags and how to unmask them.

**Comment by mittorn** [comment]
UXP does not seems to support gtk3 at all, it is only theme support

**Comment by Massimo-B** [comment]
https://www.palemoon.org/releasenotes.shtml in v29.0.0 (2021-02-02) says
> We now offer official GTK3 builds for Linux alongside the GTK2 builds.
