### ISSUE TITLE
Add GCC 9.3 as supported compiler

### ISSUE THREAD

**Issue by jeandestouches** [deu/palemoon-overlay#88]
Hi,
GCC 9.3 has been out for quite a while and so far compile palemoon without issue. What about adding it to the supported compiler list ?
This is of course not an emergency. For now I'm overriding the variable in make.conf. Maybe for the next palemoon update ?
Thanks!

**Comment by deu** [comment]
Closed by a3c55e23cac2de9c76f7c3021d586154886d614b.

**Comment by wedhusgembel** [comment]
latest version doesnt get GCC 9.3 again, why?
